#DataSource
spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/pro?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver