# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
# Spring配置
spring:
  profiles:
    active: druid