package com.tmax.domain;



import com.github.autoId.annotation.AutoId;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Res_Order
 *
 * @mbg.generated do_not_delete_during_merge
 */


public class ResOrder implements Serializable {
    /**
     * Database Column Remarks:
     *   订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Res_Order.o_id
     *
     * @mbg.generated
     */
    @AutoId
    private Long oId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Res_Order.o_vid
     *
     * @mbg.generated
     */
    private String oVid;

    /**
     * 订单人名字
     */
    private String oPerName;

    /**
     * Database Column Remarks:
     *   订单地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Res_Order.o_addr
     *
     * @mbg.generated
     */
    private String oAddr;

    /**
     * Database Column Remarks:
     *   订单人电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Res_Order.o_telno
     *
     * @mbg.generated
     */
    private String oTelno;

    /**
     * Database Column Remarks:
     *   订单补充
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Res_Order.o_detail
     *
     * @mbg.generated
     */
    private String oDetail;

    /**
     * Database Column Remarks:
     *   商品ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Res_Order.o_pid
     *
     * @mbg.generated
     */
    private Integer oPid;


    private String oVirCode;

    /**
     * Database Column Remarks:
     *   物流公司
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Res_Order.o_transform_company
     *
     * @mbg.generated
     */
    private String oTransformCompany;

    /**
     * Database Column Remarks:
     *   物流号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Res_Order.o_transform_num
     *
     * @mbg.generated
     */
    private String oTransformNum;

    /**
     * Database Column Remarks:
     *   订单创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Res_Order.o_creatime
     *
     * @mbg.generated
     */
    private Date oCreatime;

    /**
     * Database Column Remarks:
     *   订单更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Res_Order.o_updatetime
     *
     * @mbg.generated
     */
    private Date oUpdatetime;

    /**
     * Database Column Remarks:
     *   订单有效状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Res_Order.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Res_Order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public Long getoId() {
        return oId;
    }

    public void setoId(Long oId) {
        this.oId = oId;
    }

    public String getoVid() {
        return oVid;
    }

    public void setoVid(String oVid) {
        this.oVid = oVid;
    }

    public String getoPerName() {
        return oPerName;
    }

    public void setoPerName(String oPerName) {
        this.oPerName = oPerName;
    }

    public String getoAddr() {
        return oAddr;
    }

    public void setoAddr(String oAddr) {
        this.oAddr = oAddr;
    }

    public String getoTelno() {
        return oTelno;
    }

    public void setoTelno(String oTelno) {
        this.oTelno = oTelno;
    }

    public String getoDetail() {
        return oDetail;
    }

    public void setoDetail(String oDetail) {
        this.oDetail = oDetail;
    }

    public Integer getoPid() {
        return oPid;
    }

    public void setoPid(Integer oPid) {
        this.oPid = oPid;
    }

    public String getoVirCode() {
        return oVirCode;
    }

    public void setoVirCode(String oVirCode) {
        this.oVirCode = oVirCode;
    }

    public String getoTransformCompany() {
        return oTransformCompany;
    }

    public void setoTransformCompany(String oTransformCompany) {
        this.oTransformCompany = oTransformCompany;
    }

    public String getoTransformNum() {
        return oTransformNum;
    }

    public void setoTransformNum(String oTransformNum) {
        this.oTransformNum = oTransformNum;
    }

    public Date getoCreatime() {
        return oCreatime;
    }

    public void setoCreatime(Date oCreatime) {
        this.oCreatime = oCreatime;
    }

    public Date getoUpdatetime() {
        return oUpdatetime;
    }

    public void setoUpdatetime(Date oUpdatetime) {
        this.oUpdatetime = oUpdatetime;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }
}